(cl:defpackage det_service_lab-srv
  (:use )
  (:export
   "DETERMINANTCOUNTERSERV"
   "<DETERMINANTCOUNTERSERV-REQUEST>"
   "DETERMINANTCOUNTERSERV-REQUEST"
   "<DETERMINANTCOUNTERSERV-RESPONSE>"
   "DETERMINANTCOUNTERSERV-RESPONSE"
  ))

