// Generated by gencpp from file det_service_lab/DeterminantCounterServ.msg
// DO NOT EDIT!


#ifndef DET_SERVICE_LAB_MESSAGE_DETERMINANTCOUNTERSERV_H
#define DET_SERVICE_LAB_MESSAGE_DETERMINANTCOUNTERSERV_H

#include <ros/service_traits.h>


#include <det_service_lab/DeterminantCounterServRequest.h>
#include <det_service_lab/DeterminantCounterServResponse.h>


namespace det_service_lab
{

struct DeterminantCounterServ
{

typedef DeterminantCounterServRequest Request;
typedef DeterminantCounterServResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeterminantCounterServ
} // namespace det_service_lab


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::det_service_lab::DeterminantCounterServ > {
  static const char* value()
  {
    return "3e8a6a602544480a67a9f07dbdeee698";
  }

  static const char* value(const ::det_service_lab::DeterminantCounterServ&) { return value(); }
};

template<>
struct DataType< ::det_service_lab::DeterminantCounterServ > {
  static const char* value()
  {
    return "det_service_lab/DeterminantCounterServ";
  }

  static const char* value(const ::det_service_lab::DeterminantCounterServ&) { return value(); }
};


// service_traits::MD5Sum< ::det_service_lab::DeterminantCounterServRequest> should match
// service_traits::MD5Sum< ::det_service_lab::DeterminantCounterServ >
template<>
struct MD5Sum< ::det_service_lab::DeterminantCounterServRequest>
{
  static const char* value()
  {
    return MD5Sum< ::det_service_lab::DeterminantCounterServ >::value();
  }
  static const char* value(const ::det_service_lab::DeterminantCounterServRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::det_service_lab::DeterminantCounterServRequest> should match
// service_traits::DataType< ::det_service_lab::DeterminantCounterServ >
template<>
struct DataType< ::det_service_lab::DeterminantCounterServRequest>
{
  static const char* value()
  {
    return DataType< ::det_service_lab::DeterminantCounterServ >::value();
  }
  static const char* value(const ::det_service_lab::DeterminantCounterServRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::det_service_lab::DeterminantCounterServResponse> should match
// service_traits::MD5Sum< ::det_service_lab::DeterminantCounterServ >
template<>
struct MD5Sum< ::det_service_lab::DeterminantCounterServResponse>
{
  static const char* value()
  {
    return MD5Sum< ::det_service_lab::DeterminantCounterServ >::value();
  }
  static const char* value(const ::det_service_lab::DeterminantCounterServResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::det_service_lab::DeterminantCounterServResponse> should match
// service_traits::DataType< ::det_service_lab::DeterminantCounterServ >
template<>
struct DataType< ::det_service_lab::DeterminantCounterServResponse>
{
  static const char* value()
  {
    return DataType< ::det_service_lab::DeterminantCounterServ >::value();
  }
  static const char* value(const ::det_service_lab::DeterminantCounterServResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DET_SERVICE_LAB_MESSAGE_DETERMINANTCOUNTERSERV_H
